function makeList() {
    const movieListConst = ["1408",
"30 Days of Night",
"28 days late",
"A dark song",
"A Girl Walks Home Alone At Night",
"A tale of Two Sisters",
"Absentia",
"Alice in borderland",
"Amusement",
"Animal",
"Antlers",
"Antrum",
"Apostle",
"Astor",
"Audition : found footage film",
"Await Further Instructions",
"Bad Boy Bubby",
"Baskin",
"Banshee Chapter",
"Be My Cat",
"Beast",
"Beyond the Black Rainbow",
"Black Christmas",
"Black Mountain Side",
"Body Snatchers",
"Bone tomahawk",
"Border",
"Butterfly Kisses",
"Cabin Fever",
"Cargo",
"Candy man",
"Caveat",
"Censor",
"Children Of Men",
"City of Lost Children",
"Color out of space",
"Come True",
"Crimson Peak",
"Curse if Aurore",
"Dark Was the Night",
"Darling",
"Death of a Vlogger",
"The Dark Tapes",
"Dead alive",
"Dead End",
"Dead Ringers",
"Deliverance",
"Digging Up the Marrow",
"Doctor Sleep",
"Dog Soldiers",
"Eden Lake",
"Exhibit A",
"Fear Street Pt Three: 1666",
"Feast",
"Forgotten",
"Found Footage 3D",
"Freaky",
"Gaia",
"Geralds game",
"Ghost Stories",
"Ginger Snaps 2",
"Gretal and hansel",
"Grindhouse",
"Goodnight Mommy",
"Good Neighbors",
"Gwen",
"Gwoemul",
"Hagazussa",
"Happy death day 1",
"Happy death day 2 u",
"Hatching",
"Honeymoon",
"House of wax",
"Housebound",
"Hunter Hunter",
"Relic",
"Im the pretty thing that lives in the house",
"I saw the devil",
"Impetigor",
"I’m Thinking of EndingThings",
"In the Earth",
"Incident in a Ghostland",
"Ink",
"It comes at night",
"It follows",
"Jugface",
"Kill list",
"Lake mungo",
"Last night in Soho",
"Lamb",
"Last shift",
"Leaving D.C.",
"Let Me In",
"Let The Right One In",
"Let Us Prey",
"Mandy",
"Martyrs",
"Meat train",
"Memento",
"Memories of Murder",
"Midnight mass",
"Misery",
"Mother",
"Mulholland Drive",
"Murder Death Koreatown",
"My heart can’t beat unless you tell it to",
"Night of The Living Dead",
"No one gets out alive",
"Nocturnal Animals",
"Noroi: The Curse",
"Oculus",
"Odd Thomas",
"Perfection",
"Personal Shopper",
"Pet cemetery",
"Pig",
"Predestination",
"Pontypool",
"Possessor",
"Psycho Goreman",
"Pyrwacket",
"Quarantine",
"Raw",
"Re-Animator",
"Red State",
"REC",
"Rust Creek",
"Saint Maud",
"Sator",
"Satan’s Slave",
"Savageland",
"Session 9",
"Shelley",
"Sputnik",
"Starfish",
"Starry eyes",
"Strangers",
"Suspiria",
"Swallow",
"Terrified",
"Triangle",
"The Age of Adeline",
"The Black Phone",
"The Bay",
"The Boy Behind The Door",
"The Cell",
"The Conspiracy",
"The Cursed",
"The Dark",
"The dark and the wicked",
"The deeper you dig",
"The Djinn",
"The Beach House",
"The Beta Test",
"The Borderlands",
"The Curse of Aurore",
"The Dark and the Wicked",
"The Devils Candy",
"The Devil’s Doorway",
"The Empty Man",
"The evil dead",
"The Eye",
"The feast",
"The Fly",
"The Green Knight",
"The Guest",
"The Hallow",
"The Hole In The Ground",
"The House That Jack Built",
"The Houses October built 60%",
"The Innkeepers",
"The Invitation",
"The lodge",
"The Lost Footage of Leah Sullivan",
"The Loved Ones",
"The Mortuary Collection",
"The Night House",
"The Northman",
"The Others",
"The People Under the Stairs",
"The Pughkeepsie Tapes",
"The puppet master",
"The Queen of Black Magic",
"The Road",
"The Ruins",
"The Sacrament",
"The Seventh Seal",
"The Shrine",
"The Similars",
"The Tunnel",
"The void",
"The Wind",
"The Wretched",
"Thelma",
"They look like people",
"Thirst",
"Triangle",
"Truck r’ treat",
"Under The Shadow",
"Under The Skin",
"Unfriended: Dark Web",
"VHS 94",
"Videodrome",
"Violation",
"We Need to Do Something",
"We need to talk about kevin",
"Werewolves Within",
"What Josiah Saw",
"Willow Creek",
"Wolf of snow hollow",
"Wrong Turn 2: Dead End",
"Wyrmwood",
"YellowBrickRoad",
"You’re Next"
];

// Make a container element for the list
let listContainer = document.createElement('div');

// Make the list
let listElement = document.createElement('ul');
listElement.id="movieList";

// Make the list item
let listItem = document.createElement('li');

// Add it to the page
document.body.appendChild(listContainer);
listContainer.appendChild(listElement);

// Set up a loop that goes through the items in listItems one at a time
let numberOfListItems = movieListConst.length;
for (let i = 0; i < numberOfListItems; ++i) {
    
    
    // Add the item text

// Use this if the array elements contain HTML
    // listItem.innerHTML = listData[i];
    // If not, use the line below

// Use this if the array elements are text only
    listItem.textContent = movieListConst[i];

    // Add listItem to the listElement
    listElement.appendChild(listItem);

    // Reset the list item
    listItem = document.createElement('li');
    }
}
// Usage
makeList();